### ISSUE TITLE
Cannot play with friends against BWMetaAi

### ISSUE THREAD

**Issue by MBguity** [jncraton/BWMetaAI#21]
I can play against the AI myself using this method now.
> Samase works great for me. Didn't notice any problems. The timings in my custom builds still work. I encourage everyone to give this a try.
> 
> 1. Get [Samase](http://www.staredit.net/topic/17430/0/)
> 2. Get aiscript.bin from BWMetaAI's releases page
> 3. Make the directory layout like this:
>    StarCraft\x86\StarCraft.exe
>    StarCraft\x86\sesame.exe
>    StarCraft\x86\_custom_\scripts\aiscript.bin
> 4. Make a shortcut to sasame.exe and add _custom_ as a command line parameter.
> 
> The name _custom_ can be anything you want. Just make sure the directory and parameter match.

Now however when I try to start a game over either Battle.net or LAN with a friend who also has set up the AI in the way mentioned above, **we both get dropped from each others games at the exact time when the AI's first say something in all chat.** 

We used to play against this AI together (Its very fun on big maps) when all we had to do was replace the patch_rt files on everyone's computers. Everything ran fine, and it was the most enjoyable comp stomps I had ever played (considering it was actually a challenge), but now I am wearing a mild sad face as this is seemingly no long possible D:

In case you are wondering, both me and my friend can individually play against the new AI (the messages appear etc) but just cannot play together.

I hope someone can help! And if not, I'll just have to live with.... Starcraft 2... (Dies a bit inside)

**Comment by jncraton** [comment]
Thanks for getting in touch about this. I'm glad that you've had so much fun playing against this AI!

I unfortunately have limited time to commit to this project, so I don't have any suggestions on a fix for you at the moment. Certainly make sure that everyone playing is using the exact same version of Samase and aiscript.bin if you have not already.

I did confirm that the way that you are running the game using Samase works for me locally. I'm not certain what would be causing a desync for you in multiplayer, but I haven't used this in multiplayer since Samase became necessary for playing. It's entirely possible that one of the recent patches adjusted something in a way that now leads modified MPQs to cause desyncs in multiplayer, but I don't follow the modding scene well enough to know if this is the case.

I'll update this issue if I learn of a way to fix this. In the meantime, the only workaround that I am aware of is to play on 1.16. T_T

**Comment by MBguity** [comment]
Ok, Thanks for the quick reply. I hope something gets figured out soon!

**Comment by T1mL3arn** [comment]
Just want to note that there is no drop problem with remastered now. Tested on version 1.23.6 with my friend and all worked fine.
