### ISSUE TITLE
I found the wrong word.

### ISSUE THREAD

**Issue by ajujoa** [jncraton/BWMetaAI#45]
tools\abbrevs.json
 339:     "Zerg Flyer Caparace"
 340:         "Flyer Caparace"

tools\Libs\Data\Icons.txt
 297: Pneumatized Caparace
 298: Zerg Caparace
 299: Flyer Caparace

tools\Libs\Data\Upgrades.txt
 5: Zerg Flyer Caparace 

Carapace.

**Comment by jncraton** [comment]
I've changed this in the abbrevs file in this project so that names without the `Zerg` prefix should work now. I'm leaving the others alone, as they come directly from [PyMS](https://github.com/search?q=repo%3Apoiuyqwert%2FPyMS%20Caparace&type=code). They could theoretically be changed there, but there may be historical reasons why changing those is not worth it.

Within this project, the correct spelling should now work everywhere.
